# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  pytest:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/mariadb:10.2
        environment:
          - MYSQL_USER: root
          - MYSQL_HOST: 127.0.0.1
          - MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - run:
          name: Copy config.json
          command: |
            cp examples/config.json .
      - run:
          command: |
            . venv/bin/activate
            pytest
  jest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install Node dependencies
          command: "npm install --dev"
      - run:
          name: Copy default config
          command: cp examples/config.json ./
      - run:
          name: Run react tests
          command: "npm test"
workflows:
  version: 2
  pytest_and_jest:
    jobs:
      - pytest
      - jest
